### ISSUE TITLE
Only outputs error to console on an unresolvable path, breaks build tool integration

### ISSUE THREAD

**Issue by AlexGilleran** [jrburke/r.js#684]
I've been using r.js through the grunt-contrib-requirejs plugin, which works great except that if I try to require a module with an incorrect path, an error message will be output to the console and the build will immediately quit - but grunt won't pick this up and report that the build failed.

The reason is that grunt-contrib-requirejs listens to the log output from r.js and fails on anything starting with "Error":

```
  requirejs.define('node/print', [], function() {
    return function print(msg) {
      if (msg.substring(0, 5) === 'Error') {
        grunt.log.errorlns(msg);
        grunt.fail.warn('RequireJS failed.');
      } else {
        grunt.log.oklns(msg);
      }
    };
  });
```

... but for certain errors r.js doesn't output to the logger at all: 

(x.js:337)

```
errback = errback || function (err) {
    // Using console here since logger may have
    // turned off error logging. Since quit is
    // called want to be sure a message is printed.
    console.log(err);
    quit(1);
 };
```

If `logger.error(err);` is added to this function then it works perfectly with grunt. Is there any possibility of adding this, even though it would mean the error would be output twice in some cases?

The case that made me aware of this is getting paths wrong - a bad merge resulted in a view trying to require in `lessonUpdated.html` and `lessonCreated.html` instead of `lessonUpdatedMessage.html` and `lessonCreatedMessage.html`.

```
The following modules share the same URL. This could be a misconfiguration if that URL only has one anonymous module in it:
undefined: text!home/activities/lessonCreated.html, text!home/activities/lessonUpdated.html
    at Function.build.checkForErrors (c:\projects\core\js\node_modules\grunt-contrib-requirejs\node_modules\requirejs\bin\r.js:25510:19)
]
  originalError:
   [Error: Loader plugin did not call the load callback in the build: text
   Module loading did not complete for: main, home/Router, home/DeprecatedHomeTabView, home/DeprecatedActivityView, home/activities/LessonCreatedView, text!home/activities/lessonCreated.html, home/activities/LessonUpdatedView, text!home/activities/lessonUpdated.html
   The following modules share the same URL. This could be a misconfiguration if that URL only has one anonymous module in it:
   undefined: text!home/activities/lessonCreated.html, text!home/activities/lessonUpdated.html] }
```
