### ISSUE TITLE
Regression on the "Embedded Test" since 1.0.2

### ISSUE THREAD

**Issue by ericanderson** [jrburke/r.js#202]
I've been trying to get require.js to play nicely with node for a few hours now and I have traced it down to the embedded test working until the 1.0.2 release.

I will look into the changes between 1.0.1 -> 1.0.2 to figure out if I can trace it down more. Starting the ticket now.

Note, the example works in 1.0.1 and in 1.0.2 and beyond you get the error:

```
Error: Calling node's require("coffee/foo") failed with error: Error: Cannot find module 'coffee/foo'
```
